dist: xenial
addons:
  snaps:
  - hugo
  - rsync

branches:
  only:
  - master
  - community

before_install:
- openssl aes-256-cbc -K $encrypted_cf7601538c18_key -iv $encrypted_cf7601538c18_iv
  -in deploy_key.enc -out ./deploy_key -d
- chmod 600 ./deploy_key
- ssh-add ./deploy_key

script:
- hugo

after_success:
- rsync -avz --delete public/ travis@${HOST}:/var/www/burtonr.dev
