name: Build and Release

on:
  push:
    branches: 
      - actions-test
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      id: setup_hugo
      uses: peaceiris/actions-hugo@v2.3.2
      with:
        hugo-version: 'latest'

    - name: Hugo Build
      id: hugo_build
      run: hugo --minify

    - name: Archive Files
      id: archive_files
      run: (cd public && zip -qr site.zip . && mv site.zip ../)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
